---
title: Hotels in Key West Florida | 24 North Hotel Key West
description: 
url: https://www.24northhotel.com
booking_widget_url: https://24northhotel.reztrip.com/mobile
permalink: pretty
markdown: kramdown
default_lang: en
languages:
- en
include:
- _pages
data_paginate:
  per_page: 4
  data: blog
  path: blog/page:num
  pagination_template: blog/index.html
  sort_field: date
  sort_reverse: true
page_gen:
- data: blog
  template: blog-details
  dir: blog
- data: category
  template: category-list
  dir: blog/category
- data: standalone
  template: standalone-single
  dir: ''
exclude:
- lib
- config.rb
- ".sass-cache"
- Capfile
- config
- log
- Rakefile
- Rakefile.rb
- tmp
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- node_modules
- gulpfile.js
- package.json
- media.json
- models.json
- sitemap.json
i18n_dir:
- _ttio_templates/no-bedrock-cp/_locales
- _locales
layouts_dir:
- _ttio_templates/no-bedrock-cp/_layouts
- _layouts
data_dir:
- _ttio_templates/no-bedrock-cp/_data
- _data
includes_dir:
- _includes
- _ttio_templates/no-bedrock-cp/_includes
